# Generated by Django 4.1.5 on 2023-01-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='contract_id',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
    ]
